from __future__ import annotations

from pathlib import Path

from .palette import load as load_palette
from .paths import Paths


def extension_target(paths: Paths) -> Path:
    return paths.data_home / "nautilus-python/extensions/omarchy_palette.py"


def css_target(paths: Paths) -> Path:
    cache = paths.cache_root or paths.home / ".cache"
    return cache / "thpm/nautilus/nautilus.css"


def nautilus_python_available() -> bool:
    roots = (
        Path("/usr/lib/nautilus/extensions-4"),
        Path("/usr/lib64/nautilus/extensions-4"),
    )
    return any(
        (root / "libnautilus-python.so").is_file()
        or any(root.glob("libnautilus-python.so.*"))
        for root in roots
    )


def _rgba(value: str, alpha: float) -> str:
    value = value.removeprefix("#")
    red, green, blue = (int(value[index : index + 2], 16) for index in (0, 2, 4))
    return f"rgba({red},{green},{blue},{alpha})"


def _luminance(value: str) -> float:
    value = value.removeprefix("#")

    def channel(index: int) -> float:
        component = int(value[index : index + 2], 16) / 255
        return (
            component / 12.92
            if component <= 0.03928
            else ((component + 0.055) / 1.055) ** 2.4
        )

    return 0.2126 * channel(0) + 0.7152 * channel(2) + 0.0722 * channel(4)


def render_css(paths: Paths) -> str:
    colors = load_palette(paths.current_theme / "colors.toml")
    background = colors["bg"]
    foreground = colors["fg"]
    dark_bg = colors["dark_bg"]
    darker_bg = colors["darker_bg"]
    lighter_bg = colors["lighter_bg"]
    accent = colors.get("accent", colors["blue"])
    muted = colors["muted"]
    red = colors["red"]
    green = colors["green"]
    yellow = colors["yellow"]
    accent_fg = "#ffffff" if _luminance(accent) < 0.45 else background
    try:
        theme_name = " ".join(paths.current_theme_name.read_text().splitlines()).strip()
        theme_name = (theme_name or "unknown").replace("*/", "* /")[:160]
    except OSError:
        theme_name = "unknown"
    shade = _rgba("#000000", 0.18 if colors["mode"] == "light" else 0.36)
    scrollbar = (
        "rgba(255,255,255,0.12)"
        if colors["mode"] == "dark"
        else "rgba(0,0,0,0.15)"
    )
    definitions = (
        ("window_bg_color", background),
        ("window_fg_color", foreground),
        ("view_bg_color", background),
        ("view_fg_color", foreground),
        ("headerbar_bg_color", background),
        ("headerbar_fg_color", foreground),
        ("headerbar_backdrop_color", dark_bg),
        ("headerbar_shade_color", _rgba(muted, 0.36)),
        ("headerbar_darker_shade_color", _rgba(muted, 0.6)),
        ("sidebar_bg_color", dark_bg),
        ("sidebar_fg_color", foreground),
        ("sidebar_backdrop_color", darker_bg),
        ("sidebar_shade_color", _rgba(muted, 0.25)),
        ("sidebar_border_color", _rgba(muted, 0.36)),
        ("secondary_sidebar_bg_color", darker_bg),
        ("secondary_sidebar_fg_color", foreground),
        ("secondary_sidebar_backdrop_color", darker_bg),
        ("card_bg_color", lighter_bg),
        ("card_fg_color", foreground),
        ("card_shade_color", _rgba(muted, 0.25)),
        ("dialog_bg_color", lighter_bg),
        ("dialog_fg_color", foreground),
        ("popover_bg_color", lighter_bg),
        ("popover_fg_color", foreground),
        ("thumbnail_bg_color", lighter_bg),
        ("thumbnail_fg_color", muted),
        ("accent_bg_color", accent),
        ("accent_fg_color", accent_fg),
        ("accent_color", accent),
        ("destructive_bg_color", red),
        ("destructive_fg_color", "#ffffff"),
        ("destructive_color", red),
        ("success_bg_color", green),
        ("success_fg_color", "#ffffff"),
        ("success_color", green),
        ("warning_bg_color", yellow),
        ("warning_fg_color", background),
        ("warning_color", yellow),
        ("error_bg_color", red),
        ("error_fg_color", "#ffffff"),
        ("error_color", red),
        ("shade_color", shade),
        ("scrollbar_outline_color", scrollbar),
    )
    lines = [
        "/* Generated by THPM's nautilus-palette integration",
        f"   from Omarchy theme '{theme_name}'. Do not edit. */",
        "",
        *(f"@define-color {name} {value};" for name, value in definitions),
        "",
    ]
    return "\n".join(lines)
