"""Steam/steam-adwaita data contract; never launch or terminate the client."""
from __future__ import annotations

import json
import re
from pathlib import Path

from .paths import Paths

CSS_PATH = Path("steamui/adwaita/colorthemes/omarchy/omarchy.css")
LOADER_PATH = Path("steamui/libraryroot.custom.css")
LIBRARY_PATH = Path("steamui/css/library.css")
PALETTE_IMPORT = 'https://steamloopback.host/adwaita/colorthemes/omarchy/omarchy.css'


def source_path(paths: Paths) -> Path:
    return paths.home / ".local/share/steam-adwaita/adwaita/colorthemes/omarchy/omarchy.css"


def roots(paths: Paths) -> list[Path]:
    candidates = (
        ".steam/steam", ".local/share/Steam",
        ".var/app/com.valvesoftware.Steam/.steam/steam",
        "snap/steam/common/.steam/steam",
    )
    found = set()
    for name in candidates:
        root = (paths.home / name).resolve()
        if (root / LIBRARY_PATH).is_file():
            if not root.is_relative_to(paths.home.resolve()):
                raise RuntimeError(f"steam: installation outside HOME is unsupported: {root}")
            found.add(root)
    return sorted(found)


def render(palette: dict[str, str]) -> str:
    def rgb(key: str) -> str:
        color = palette.get(key, palette["blue"]) if key == "accent" else palette[key]
        return ",".join(str(int(color[i:i + 2], 16)) for i in (1, 3, 5))

    roles = {
        "accent-bg": "accent", "accent-fg": "bg", "accent": "accent",
        "destructive-bg": "red", "destructive-fg": "fg", "destructive": "red",
        "success-bg": "green", "success-fg": "bg", "success": "green",
        "warning-bg": "yellow", "warning-fg": "bg", "warning": "yellow",
        "error-bg": "red", "error-fg": "fg", "error": "red",
        "window-bg": "bg", "window-fg": "fg", "view-bg": "bg", "view-fg": "fg",
        "headerbar-bg": "bg", "headerbar-fg": "fg", "headerbar-border": "muted",
        "headerbar-backdrop": "bg", "sidebar-bg": "dark_bg", "sidebar-fg": "fg",
        "sidebar-backdrop": "dark_bg", "secondary-sidebar-bg": "darker_bg",
        "secondary-sidebar-fg": "fg", "card-bg": "lighter_bg", "card-fg": "fg",
        "dialog-bg": "bg", "dialog-fg": "fg", "popover-bg": "bg",
        "popover-fg": "fg", "thumbnail-bg": "bg",
    }
    lines = ["/* Generated by THPM from the active Omarchy semantic palette */", ":root {"]
    lines.extend(f"    --adw-{role}-rgb: {rgb(key)} !important;" for role, key in roles.items())
    for role in ("headerbar-shade", "sidebar-shade", "shade"):
        lines.extend((f"    --adw-{role}-rgb: 0,0,0 !important;", f"    --adw-{role}-a: 0.36 !important;"))
    lines.extend(("    --adw-card-bg-a: 1 !important;", "}", ""))
    return "\n".join(lines)


def _imports(css: str) -> set[str]:
    uncommented = re.sub(r"/\*.*?\*/", "", css, flags=re.DOTALL)
    return set(re.findall(r'@import\s+url\([\"\']([^\"\']+)[\"\']\)\s*;', uncommented))


def validate(root: Path, css: str) -> None:
    try:
        installed = root / CSS_PATH
        loader = (root / LOADER_PATH).read_text()
        library = (root / LIBRARY_PATH).read_text()
        base = root / "steamui/adwaita/adwaita.css"
        if installed.is_symlink() or installed.read_text() != css:
            raise ValueError("installed Omarchy stylesheet does not match the active palette")
        if PALETTE_IMPORT not in _imports(loader):
            raise ValueError("Steam custom loader does not import the Omarchy stylesheet")
        if "https://steamloopback.host/adwaita/adwaita.css" not in _imports(loader) or not base.is_file():
            raise ValueError("Steam custom loader is missing the Adwaita base")
        if not library.startswith("/*patched*/\n") or "https://steamloopback.host/libraryroot.custom.css" not in _imports(library):
            raise ValueError("Steam library CSS does not consume the custom loader")
        if "https://steamloopback.host/css/library.original.css" not in _imports(library) or not (root / "steamui/css/library.original.css").is_file():
            raise ValueError("Steam original library CSS is missing")
    except (OSError, UnicodeError, ValueError) as exc:
        raise RuntimeError(f"steam: output validation failed: {exc}") from exc


def manifest_path(paths: Paths) -> Path:
    return paths.managed_asset_state_dir / "steam-outputs.json"


def read_manifest(paths: Paths) -> list[Path]:
    path = manifest_path(paths)
    if not path.exists() and not path.is_symlink():
        return []
    try:
        if path.is_symlink():
            raise ValueError("symlink manifest")
        data = json.loads(path.read_text())
        if not isinstance(data, list) or not all(isinstance(value, str) for value in data):
            raise ValueError("expected path list")
        targets = [Path(value) for value in data]
        for target in targets:
            # The only source output is omarchy.css; installed outputs are under
            # steamui. Constrain recovery paths and refuse redirected parents.
            relative = target.relative_to(paths.home.resolve())
            if ".." in relative.parts or target != target.absolute():
                raise ValueError("unsafe recovery path")
            if target != source_path(paths):
                if "steamui" not in relative.parts:
                    raise ValueError("unexpected recovery target")
                suffix = Path(*relative.parts[relative.parts.index("steamui") + 1:])
                if not (suffix.parts and suffix.parts[0] == "adwaita") and suffix not in {
                    Path("libraryroot.custom.css"), Path("css/library.css"), Path("css/library.original.css"),
                }:
                    raise ValueError("unexpected recovery target")
            if target.parent.resolve() != target.parent:
                raise ValueError("redirected recovery parent")
        return targets
    except (OSError, UnicodeError, ValueError) as exc:
        raise RuntimeError(f"steam: invalid restoration manifest: {path}: {exc}") from exc
