/** Generated by Omarchy for THPM. */
:root { --background-primary: {{ background }}; --background-secondary: {{ dark_background }}; --background-tertiary: {{ darker_background }}; --text-normal: {{ foreground }}; --text-muted: {{ muted }}; --brand-experiment: {{ blue }}; --status-positive: {{ green }}; --status-warning: {{ yellow }}; --status-danger: {{ red }}; }
