{
  "schemaVersion": 1,
  "source": "thpm",
  "theme": {
    "name": "omarchy-current",
    "label": "Omarchy Current",
    "description": "Generated from the active Omarchy theme",
    "colors": {
      "background": "{{ bg }}",
      "foreground": "{{ fg }}",
      "card": "{{ dark_bg }}",
      "cardForeground": "{{ fg }}",
      "muted": "{{ darker_bg }}",
      "mutedForeground": "{{ muted }}",
      "popover": "{{ dark_bg }}",
      "popoverForeground": "{{ fg }}",
      "primary": "{{ blue }}",
      "primaryForeground": "{{ bright_fg }}",
      "secondary": "{{ lighter_bg }}",
      "secondaryForeground": "{{ fg }}",
      "accent": "{{ magenta }}",
      "accentForeground": "{{ bright_fg }}",
      "border": "{{ muted }}",
      "input": "{{ lighter_bg }}",
      "ring": "{{ blue }}",
      "midground": "{{ blue }}",
      "midgroundForeground": "{{ bright_fg }}",
      "composerRing": "{{ blue }}",
      "destructive": "{{ red }}",
      "destructiveForeground": "{{ bright_fg }}",
      "sidebarBackground": "{{ dark_bg }}",
      "sidebarBorder": "{{ muted }}",
      "userBubble": "{{ darker_bg }}",
      "userBubbleBorder": "{{ muted }}"
    },
    "darkColors": {
      "background": "{{ bg }}",
      "foreground": "{{ fg }}",
      "card": "{{ dark_bg }}",
      "cardForeground": "{{ fg }}",
      "muted": "{{ darker_bg }}",
      "mutedForeground": "{{ muted }}",
      "popover": "{{ dark_bg }}",
      "popoverForeground": "{{ fg }}",
      "primary": "{{ blue }}",
      "primaryForeground": "{{ bright_fg }}",
      "secondary": "{{ lighter_bg }}",
      "secondaryForeground": "{{ fg }}",
      "accent": "{{ magenta }}",
      "accentForeground": "{{ bright_fg }}",
      "border": "{{ muted }}",
      "input": "{{ lighter_bg }}",
      "ring": "{{ blue }}",
      "midground": "{{ blue }}",
      "midgroundForeground": "{{ bright_fg }}",
      "composerRing": "{{ blue }}",
      "destructive": "{{ red }}",
      "destructiveForeground": "{{ bright_fg }}",
      "sidebarBackground": "{{ dark_bg }}",
      "sidebarBorder": "{{ muted }}",
      "userBubble": "{{ darker_bg }}",
      "userBubbleBorder": "{{ muted }}"
    },
    "terminal": {
      "foreground": "{{ fg }}",
      "cursor": "{{ cyan }}",
      "selectionBackground": "{{ selection }}",
      "black": "{{ bg }}",
      "red": "{{ red }}",
      "green": "{{ green }}",
      "yellow": "{{ yellow }}",
      "blue": "{{ blue }}",
      "magenta": "{{ magenta }}",
      "cyan": "{{ cyan }}",
      "white": "{{ fg }}",
      "brightBlack": "{{ muted }}",
      "brightRed": "{{ bright_red }}",
      "brightGreen": "{{ bright_green }}",
      "brightYellow": "{{ bright_yellow }}",
      "brightBlue": "{{ bright_blue }}",
      "brightMagenta": "{{ bright_magenta }}",
      "brightCyan": "{{ bright_cyan }}",
      "brightWhite": "{{ bright_fg }}"
    },
    "darkTerminal": {
      "foreground": "{{ fg }}",
      "cursor": "{{ cyan }}",
      "selectionBackground": "{{ selection }}",
      "black": "{{ bg }}",
      "red": "{{ red }}",
      "green": "{{ green }}",
      "yellow": "{{ yellow }}",
      "blue": "{{ blue }}",
      "magenta": "{{ magenta }}",
      "cyan": "{{ cyan }}",
      "white": "{{ fg }}",
      "brightBlack": "{{ muted }}",
      "brightRed": "{{ bright_red }}",
      "brightGreen": "{{ bright_green }}",
      "brightYellow": "{{ bright_yellow }}",
      "brightBlue": "{{ bright_blue }}",
      "brightMagenta": "{{ bright_magenta }}",
      "brightCyan": "{{ bright_cyan }}",
      "brightWhite": "{{ bright_fg }}"
    }
  }
}
