/** Generated by Omarchy for THPM. */
:root { --background-primary: {{ bg }}; --background-secondary: {{ dark_bg }}; --background-tertiary: {{ darker_bg }}; --text-normal: {{ fg }}; --text-muted: {{ muted }}; --brand-experiment: {{ blue }}; --status-positive: {{ green }}; --status-warning: {{ yellow }}; --status-danger: {{ red }}; }
