# Generated by Omarchy from a THPM-owned template.
set -gx THPM_THEME_BG "{{ background }}"
set -gx THPM_THEME_FG "{{ foreground }}"
set -gx THPM_THEME_ACCENT "{{ blue }}"
set -gx THPM_THEME_MUTED "{{ muted }}"
