# Generated by Omarchy for THPM.
c.colors.webpage.bg = '{{ bg }}'
c.colors.completion.fg = '{{ fg }}'
c.colors.completion.odd.bg = '{{ dark_bg }}'
c.colors.completion.even.bg = '{{ bg }}'
c.colors.completion.match.fg = '{{ bright_blue }}'
c.colors.statusbar.normal.bg = '{{ darker_bg }}'
c.colors.statusbar.normal.fg = '{{ fg }}'
