# Generated by Omarchy from a THPM-owned template.
set -gx FZF_DEFAULT_OPTS "$FZF_DEFAULT_OPTS --color=bg:{{ bg }},bg+:{{ selection }},fg:{{ fg }},fg+:{{ bright_fg }},hl:{{ blue }},hl+:{{ bright_blue }},info:{{ cyan }},prompt:{{ magenta }},pointer:{{ orange }},marker:{{ green }},spinner:{{ yellow }},header:{{ muted }}"
