# Generated by Omarchy from a THPM-owned Superfile v1.6 theme template.

code_syntax_highlight = "catppuccin-mocha"

full_screen_fg = "{{ foreground }}"
full_screen_bg = "{{ background }}"
gradient_color = ["{{ blue }}", "{{ magenta }}"]

file_panel_fg = "{{ foreground }}"
file_panel_bg = "{{ background }}"
file_panel_border = "{{ muted }}"
file_panel_border_active = "{{ bright_blue }}"
file_panel_top_directory_icon = "{{ blue }}"
file_panel_top_path = "{{ cyan }}"
file_panel_item_selected_fg = "{{ bright_foreground }}"
file_panel_item_selected_bg = "{{ selection }}"

footer_fg = "{{ foreground }}"
footer_bg = "{{ dark_background }}"
footer_border = "{{ muted }}"
footer_border_active = "{{ blue }}"

sidebar_fg = "{{ foreground }}"
sidebar_bg = "{{ dark_background }}"
sidebar_title = "{{ blue }}"
sidebar_border = "{{ dark_foreground }}"
sidebar_border_active = "{{ bright_blue }}"
sidebar_item_selected_fg = "{{ bright_foreground }}"
sidebar_item_selected_bg = "{{ selection }}"
sidebar_divider = "{{ muted }}"

modal_fg = "{{ foreground }}"
modal_bg = "{{ dark_background }}"
modal_border_active = "{{ bright_blue }}"
modal_cancel_fg = "{{ bright_foreground }}"
modal_cancel_bg = "{{ red }}"
modal_confirm_fg = "{{ bright_foreground }}"
modal_confirm_bg = "{{ green }}"

help_menu_hotkey = "{{ blue }}"
help_menu_title = "{{ magenta }}"

cursor = "{{ bright_foreground }}"
correct = "{{ green }}"
error = "{{ red }}"
hint = "{{ cyan }}"
cancel = "{{ red }}"
