# Generated by Omarchy for THPM.
c.colors.webpage.bg = '{{ background }}'
c.colors.completion.fg = '{{ foreground }}'
c.colors.completion.odd.bg = '{{ dark_background }}'
c.colors.completion.even.bg = '{{ background }}'
c.colors.completion.match.fg = '{{ bright_blue }}'
c.colors.statusbar.normal.bg = '{{ darker_background }}'
c.colors.statusbar.normal.fg = '{{ foreground }}'
