# Generated by Omarchy from a THPM-owned template.
set -gx FZF_DEFAULT_OPTS "$FZF_DEFAULT_OPTS --color=bg:{{ background }},bg+:{{ selection }},fg:{{ foreground }},fg+:{{ bright_foreground }},hl:{{ blue }},hl+:{{ bright_blue }},info:{{ cyan }},prompt:{{ magenta }},pointer:{{ orange }},marker:{{ green }},spinner:{{ yellow }},header:{{ muted }}"
