code_syntax_highlight = "{{ blue }}"
directory_icon = "{{ blue }}"
file_panel_border = "{{ muted }}"
file_panel_border_active = "{{ bright_blue }}"
footer = "{{ foreground }}"
full_screen_bg = "{{ background }}"
metadata = "{{ muted }}"
sidebar_border = "{{ dark_foreground }}"
